kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-config-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Mi
