apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: media-pv 
spec: 
  capacity: 
    storage: 400Gi 
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage-fast 
  local:
    path: /mnt/media 
  nodeAffinity: 
    required: 
      nodeSelectorTerms: 
      - matchExpressions: 
        - key: kubernetes.io/hostname
          operator: In 
          values:
          - node4
