kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
