kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-download-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

