apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: happyhouse-web
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: happyhouse.int.volfoni.org
    http:
      paths:
      - path: /
        backend:
          serviceName: happyhouse-web
          servicePort: 80
  tls:
   - secretName: wildcard-int-volfoni-org-tls
