apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-gandi
  labels:
    app: cert-manager-webhook-gandi
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-gandi
