---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs
spec:
  replicas: 1
  exports:
  - name: fast-media-nfs
    server:
      accessMode: ReadWrite
      squash: "none"
    # A Persistent Volume Claim must be created before creating NFS CRD instance.
    persistentVolumeClaim:
      claimName: fast-media-data-claim
    resources:
      limits:
        cpu: "300m"
        memory: "256Mi"
      requests:
        cpu : "150m"
        memory: "128Mi"
  # A key/value list of annotations
  annotations:
  #  key: value
