kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-conf
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-userdata
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-addons
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-java
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-karaf
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-usb-hd-node0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

