apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: pihole.int.volfoni.org
    http:
      paths:
      - path: /
        backend:
          serviceName: pihole-web
          servicePort: 8000
  tls:
   - secretName: wildcard-int-volfoni-org-tls
